# Generated by Django 2.1.5 on 2019-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('content', models.TextField(verbose_name='内容')),
                ('auto_renew', models.BooleanField(verbose_name='自动续费')),
                ('auto_reset_bandwidth', models.BooleanField(verbose_name='自动重置带宽')),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架'), ('2', '创建'), ('3', '删除')], max_length=32, verbose_name='商品状态')),
            ],
        ),
    ]
