# Generated by Django 2.1.5 on 2019-07-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliveip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Blockip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_created=True, verbose_name='创建时间')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='IP')),
                ('name', models.CharField(max_length=30, verbose_name='服务器名')),
                ('hub', models.CharField(max_length=100, verbose_name='HUBNAME')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('type', models.CharField(choices=[('0', '独立服务器'), ('1', '场控制器服务器'), ('2', '场成员服务器')], max_length=30, null=True, verbose_name='类型')),
            ],
        ),
        migrations.AddField(
            model_name='blockip',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.ServerInfo', verbose_name='节点 '),
        ),
        migrations.AddField(
            model_name='aliveip',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.ServerInfo', verbose_name='节点 '),
        ),
    ]
