# Generated by Django 2.1.5 on 2019-07-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='优惠券名')),
                ('code', models.CharField(max_length=256, verbose_name='优惠码')),
                ('expire', models.CharField(max_length=128, verbose_name='过期时间')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Shop', verbose_name='商品')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='check_in_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后签到时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expire_time',
            field=models.DateTimeField(auto_now=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否是管理员'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.CharField(blank=True, max_length=256, verbose_name='重置总金额'),
        ),
        migrations.AddField(
            model_name='user',
            name='port',
            field=models.CharField(blank=True, max_length=16, verbose_name='端口'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', '激活'), ('2', '未激活'), ('3', '过期'), ('4', '注销')], default='2', max_length=32, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=32, verbose_name='令牌'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=256, verbose_name='密码'),
        ),
    ]
