# Generated by Django 2.1.5 on 2019-07-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharge',
            old_name='create_time',
            new_name='datetime',
        ),
    ]
