# Generated by Django 2.1.5 on 2019-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20190722_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='type',
            field=models.CharField(default='1', max_length=32, verbose_name='类型'),
        ),
    ]
