# Generated by Django 2.1.5 on 2019-08-02 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190802_1153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0003_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detectlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('text', models.TextField(verbose_name='文本')),
                ('regex', models.CharField(max_length=100, verbose_name='正则表达式规则')),
                ('type', models.CharField(choices=[('0', '明文匹配'), ('1', 'hex匹配')], max_length=30, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Detectlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.Detectlist', verbose_name='列表')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Serverinfo', verbose_name='节点')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('ip', models.GenericIPAddressField(verbose_name='登录ip')),
                ('type', models.CharField(max_length=30, verbose_name='类型')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Usertrafficlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='速率')),
                ('traffic', models.IntegerField(verbose_name='流量')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Serverinfo', verbose_name='节点')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
